name: Linux CMake build & test

on:
  push:
    branches: [ main, dev, graphics-tests ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: [ubuntu-22.04]

    container:
      image: ghcr.io/didgy74/qt_map_thesis_image:latest

    steps:
    - uses: actions/checkout@v3

    - name: Update apt
      run: apt update
      
    - name: Upgrade apt
      run: apt upgrade -y

    - name: search apt
      run: apt search imagemagick

    - name: Install ImageMagick
      run: apt install -y imagemagick

    - name: Configure CMake
      run: |
        cmake . -B build -DCMAKE_PREFIX_PATH="/qtbuild/qtbase" -DBUILD_TESTS=ON -G Ninja
        cd build
        ninja

    - name: Run CTest
      working-directory: ${{github.workspace}}/build
      run: |
        export QT_QPA_PLATFORM=offscreen
        ctest --rerun-failed --output-on-failure
